# Generated by Django 3.2.8 on 2021-10-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indicate the industry', max_length=50, null=True, unique=True, verbose_name='Industry Name')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indicate the project name', max_length=50, null=True, unique=True, verbose_name='Project Name')),
                ('start_date', models.DateField(help_text='Indicate the date the project was born', null=True, verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Indicate the date the project was deployed into production', null=True, verbose_name='End Date')),
                ('logo', models.ImageField(help_text="Provide the project's logo", null=True, upload_to='', verbose_name='Logo')),
                ('url', models.URLField(help_text="Provide the project's direction", null=True, verbose_name='Project App')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Indicate language', max_length=20, null=True, unique=True, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_type', models.CharField(choices=[('LANGUAGE', 'Language'), ('FRAMEWORK', 'Framework'), ('LIBRARY', 'Library'), ('SOFTWARE', 'Software'), ('OTHER', 'Other')], help_text='Indicate the tool type', max_length=10, null=True, verbose_name='Tool Type')),
                ('name', models.CharField(help_text='Indicate the tool name', max_length=25, null=True, verbose_name='Tool Name')),
                ('expertise', models.IntegerField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Indicate expertise level for the tool specified', null=True)),
            ],
        ),
    ]
