# Generated by Django 3.2.8 on 2021-11-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(help_text='Indicate the institution which provided the certification', max_length=100, null=True, verbose_name='Institution')),
                ('name', models.CharField(help_text='Indicate the certification name', max_length=100, null=True, verbose_name='Certification Name')),
                ('url', models.URLField(blank=True, help_text='Provide a verification url if existent', null=True, verbose_name='Verification URL')),
                ('image', models.ImageField(blank=True, help_text='Provide a certification image if no verification url is available ', null=True, upload_to='', verbose_name='Certification Image')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(help_text='Provide a project description', max_length=250, null=True, verbose_name='Project Description'),
        ),
    ]
