# Generated by Django 3.2.8 on 2021-11-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211101_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='expertise',
        ),
        migrations.AddField(
            model_name='industryknowledge',
            name='expertise_level',
            field=models.CharField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', max_length=50, null=True, verbose_name='Expertise Level'),
        ),
        migrations.AddField(
            model_name='industryknowledge',
            name='icon',
            field=models.CharField(blank=True, help_text='Provide the icon code for the specified skill', max_length=50, null=True, unique=True, verbose_name='Skill Icon Code'),
        ),
        migrations.AddField(
            model_name='speakinglanguage',
            name='expertise_level',
            field=models.CharField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', max_length=50, null=True, verbose_name='Expertise Level'),
        ),
        migrations.AddField(
            model_name='speakinglanguage',
            name='icon',
            field=models.CharField(blank=True, help_text='Provide the icon code for the specified skill', max_length=50, null=True, unique=True, verbose_name='Skill Icon Code'),
        ),
        migrations.AddField(
            model_name='tool',
            name='expertise_level',
            field=models.CharField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', max_length=50, null=True, verbose_name='Expertise Level'),
        ),
        migrations.AddField(
            model_name='tool',
            name='icon',
            field=models.CharField(blank=True, help_text='Provide the icon code for the specified skill', max_length=50, null=True, unique=True, verbose_name='Skill Icon Code'),
        ),
        migrations.AlterField(
            model_name='industryknowledge',
            name='name',
            field=models.CharField(help_text='Provide the Specified Skill Name', max_length=50, null=True, unique=True, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='speakinglanguage',
            name='name',
            field=models.CharField(help_text='Provide the Specified Skill Name', max_length=50, null=True, unique=True, verbose_name='Skill Name'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(help_text='Provide the Specified Skill Name', max_length=50, null=True, unique=True, verbose_name='Skill Name'),
        ),
    ]
