# Generated by Django 3.2.8 on 2021-12-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211115_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='institution_logo',
            field=models.ImageField(help_text='Provide the Institution Logo', null=True, upload_to='', verbose_name='Institution Logo'),
        ),
    ]
