# Generated by Django 3.2.8 on 2021-12-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_certification_institution_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industryknowledge',
            name='expertise_level',
            field=models.IntegerField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', null=True, verbose_name='Expertise Level'),
        ),
        migrations.AlterField(
            model_name='speakinglanguage',
            name='expertise_level',
            field=models.IntegerField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', null=True, verbose_name='Expertise Level'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='expertise_level',
            field=models.IntegerField(choices=[(20, 'Novice'), (40, 'Beginner'), (60, 'Skillful'), (80, 'Experienced'), (100, 'Expert')], help_text='Provide the Expertise Level for the specified skill', null=True, verbose_name='Expertise Level'),
        ),
    ]
