# Generated by Django 3.2.8 on 2022-01-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211229_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, help_text='Provide a certification image if no verification url is available', null=True, upload_to='certifications/certifications_verifications/', verbose_name='Certification Image'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='institution_logo',
            field=models.ImageField(help_text='Provide the Institution Logo', null=True, upload_to='certifications/institutions_logos/', verbose_name='Institution Logo'),
        ),
    ]
