# Generated by Django 3.2.8 on 2022-01-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220105_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(help_text="Provide the project's logo", null=True, upload_to='project_logos/', verbose_name='Logo'),
        ),
    ]
